default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>


test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>

staging:
  <<: *default

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>



